### ISSUE TITLE
NEVERMORE_PRINT_END reference largely identical to NEVERMORE_PRINT_START

### ISSUE THREAD

**Issue by EnsuingRequiem** [SanaaHamel/nevermore-controller#11]
When addressing what `NEVERMORE_PRINT_END` currently does, the documentation uses identical wording to what was used in `NEVERMORE_PRINT_START` including that the `VOC_CALIBRATION` is disabled. This seems like it is not correct.

**Comment by SanaaHamel** [comment]
Corrected by f8a05fb, thanks for catching this.
