### ISSUE TITLE
Photocatalytic Control request

### ISSUE THREAD

**Issue by nfettinger** [SanaaHamel/nevermore-controller#13]
The Stealthmax BOM indicates that the Photocatalytic Control add-on should power the fans and LEDs via a mechanical 12v relay. Due to this, support should be pivoted from a PWM control, to a simple on-off toggle accessible from klipper. When wired up, connecting the relay control to ground enables the VOC circuitry.

**Comment by SanaaHamel** [comment]
It's currently a PWM control because the test hardware being used can switch fast enough to implement a brightness control for the UV LEDs. There's no Klipper bindings at this time, only direct control via BLE, because the PC add-on hasn't yet left beta/experimental status.
