### ISSUE TITLE
Fan control Issue

### ISSUE THREAD

**Issue by gfosdike1** [SanaaHamel/nevermore-controller#14]
The fan seems to be working via a policy ok, but I have no control of it through mainsail manually. Also, the RPM is not being displayed. Any idea what I'm missing? 

[nevermore]
bt_address: 28:CD:C1:0F:3C:85
connection_initial_timeout: 0
fan_power_passive: 1
fan_power_automatic: 0.3
fan_power_coefficient: 1

fan_policy_cooldown: 600 ; 10 min
fan_policy_voc_passive_max: 300
fan_policy_voc_improve_min: 100

fan_thermal_limit_temperature_min: 50
fan_thermal_limit_temperature_max: 60
fan_thermal_limit_coefficient: 0.5

voc_gating_threshold: 300

[temperature_sensor nevermore_intake_VOC]
sensor_type: NevermoreSensor
sensor_kind: intake
plot_voc: true

[temperature_sensor nevermore_exhaust_VOC]
sensor_type: NevermoreSensor
sensor_kind: exhaust
plot_voc: true

**Comment by SanaaHamel** [comment]
No RPM/control + `connection_initial_timeout: 0` suggests the system hasn't connected over BLE. See FAQ, `NEVERMORE_STATUS`, and check your Klipper log.
