### ISSUE TITLE
requirements.txt 

### ISSUE THREAD

**Issue by O-to-the-o** [SanaaHamel/nevermore-controller#17]
Hi the requirements.txt causes issues when i try to install it, it's fixed by chaning it to:

bleak>=0.21.1, <1
janus>=1, <2
typing_extensions>=4, <5

could anyone who knows more about github look at this pls ?

Kind regards
O

**Comment by ksummers92** [comment]
Created PR here. Not sure how to link this issue though. Or link the PR here either.

**Comment by eMadman** [comment]
Thanks @ksummers92 - I'm migrating a machine to a new pi and this solved the issue.

**Comment by krompiel** [comment]
good morning gentleman. i ran into the same issue.

im terrible with linux, could i, and how would i correct this manually?

thank you

**Comment by eMadman** [comment]
> good morning gentleman. i ran into the same issue.
> 
> im terrible with linux, could i, and how would i correct this manually?
> 
> thank you
Use a text editor like nano to change requirements.txt to match what's been attached to this pull request: https://github.com/SanaaHamel/nevermore-controller/pull/18

**Comment by krompiel** [comment]
> > good morning gentleman. i ran into the same issue.
> > im terrible with linux, could i, and how would i correct this manually?
> > thank you
> 
> Use a text editor like nano to change requirements.txt to match what's been attached to this pull request: #18

well duh of course lol. stupid me. thank you sir i shall try this tonight

**Comment by matt-rendall** [comment]
Thank you! Also ran into this when migrating to a new Pi.
