### ISSUE TITLE
feature request:  usb version 

### ISSUE THREAD

**Issue by krompiel** [SanaaHamel/nevermore-controller#19]
hi. thanks for your effort so far. id like to ask if you have or would it be possible to do a usb to board (my specific situation: manta+cb1, no bluetooth) version instead of bluetooth?

**Comment by SanaaHamel** [comment]
This would require very significant effort to implement. PRs welcome, but I have no plans to implement this myself.

**Comment by thetic** [comment]
This is completed?

**Comment by SanaaHamel** [comment]
Complete as of v0.16.
