### ISSUE TITLE
Updating to v0.13 looses one set of sensors

### ISSUE THREAD

**Issue by mikeytdisco** [SanaaHamel/nevermore-controller#9]
The nevermore display in Mainsail shows "-" for the left sensor values.  Flashing back to v0.12 shows the sensor values.

**Comment by Dark360** [comment]
@mikeytdisco,

@SanaaHamel posted this on Discord to fix this issues whilst they worked on a solution.

# switch to your nevermore-controller installation
cd ~/nevermore-controller
# fetch updates for klipper module and tools
git pull
# reset the pin configuration to default. follow the on-screen instructions.
~/nevermore-controller/tools/pin-config.py --reset-default

[](https://github.com/SanaaHamel/nevermore-controller?tab=readme-ov-file#pin-assignments)

**Comment by mikeytdisco** [comment]
The work around fixed the issue.  Thanks.

**Comment by SanaaHamel** [comment]
Should also be fixed by 0.14 release.
